spring.application.name=clinical-gateway
server.port=8080

# Gateway route to Patient Data API
spring.cloud.gateway.server.webflux.routes[0].id=patientdata-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/clinical/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1


# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Keycloak JWT Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/healthtech